FROM php:8.5-cli

WORKDIR /app

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN install-php-extensions pcov

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
